name: anchor-test
on: [push]
jobs:
  run-anchor-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaobuilders/anchor-test@v1
        with:
          - anchor-version: '0.25.0'
            solana-cli-version: '1.14.3'
